name: monorepo-image-analyzer
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: backend
    env_file:
      - ./apps/backend/.env
    ports:
      - "3000:3000"
    networks:
      - appnet
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: frontend
    env_file:
      - ./apps/frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge
